#!/usr/bin/env bash
# See <https://github.com/ZeusWPI/Advent-of-Code-Aggregator>
if [[ -f "2022/$1.cpp" ]]; then
    g++ -o run -O2 "2022/$1.cpp"
else
    cabal build -O2 "exe:2022-$1"
    cp "$(cabal exec -O2 which "2022-$1")" run
fi
